### ISSUE TITLE
why giving bound for map zoom ?

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#14]
```
def update_map(self, assetId, bounds, remove_last=False):
        """Update the map with the asset overlay and removing the selected drawing controls
        
        Args:
            assetId (str): the asset ID in gee assets
            bounds (list of tuple(x,y)): coordinates of tl, bl, tr, br points
            remove_last (boolean) (optional): Remove the last layer (if there is one) before 
                                                updating the map
        """  
        if remove_last:
            self.remove_last_layer()

        self.set_zoom(bounds, zoom_out=2)
        self.centerObject(ee.FeatureCollection(assetId), zoom=self.zoom)
        self.addLayer(ee.FeatureCollection(assetId), {'color': 'green'}, name='aoi')


    def set_zoom(self, bounds, zoom_out=1):
        """ Get the proper zoom to the given bounds.

        Args:

            bounds (list of tuple(x,y)): coordinates of tl, bl, tr, br points
            zoom_out (int) (optional): Zoom out the bounding zoom

        Returns:

            zoom (int): Zoom for the given ee_asset
        """

        tl, bl, tr, br = bounds
        
        maxsize = max(haversine(tl, br), haversine(bl, tr))
        lg = 40075 #number of displayed km at zoom 1
        zoom = 1
        while lg > maxsize:
            zoom += 1
            lg /= 2

        if zoom_out > zoom:
            zoom_out = zoom - 1

        self.zoom = zoom-zoom_out

```

I don't get why you gave bounds in AND assetId in updateZoom. Is it linked to a specific application ? because if you have the assetId you can easily compute the bounds ad if you want to zoom on something else you shoud not give the assetId. 

Would you mind if I create two zooming method, one manual with bounds and zoom_out and an autmatic with assetId and an optional zoom_out ?

```
def centerAsset(assetId, zoom_out= 1):

    return self

def centerBounds(bounds, zoom_out=1):
    
    return self 
```

**Comment by ingdanielguerrero** [comment]
Actually yes, I've created this method to be linked with the "`Aoi_IO`" class (also proposed) and its method get_bounds... GEE has the option to calculate the bounds for the asset, so we do not have to transform i.e. shapefiles into shapely to get its bounds, it can be directly calculated on fly. 
I kept the "assetId" parameter name as you had previously, but I think that the correct name would be "ee_object" or something like that because most of the assets are composed of more than one feature.

I didn't add those methods directly to this class because I'm not sure if they should belong to the sepalmap class or directly to the "feature, aoi" object.

**Comment by 12rambau** [comment]
Nothing to add on the Aoi_io class it's perfect to me, and I think you add lots of method to your usage that can be very usefull for others.

I would say that the zoom must be completely handled by the sepalmap class (because someone would want to use the zoom for something else than the aoi_io). I've seen the get_bounds function it's very much more efficient indeed ;-) 

I'll go for the two separate function and we'll see how it fit with yours and my applications
