### ISSUE TITLE
the assetSelect need a reload btn 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#161]
It's the same problem as the FIleInput, if a new asset is created by the process, it won't be displayed in the list (as the list is never reevaluated)

**Comment by ingdanielguerrero** [comment]
Instead of elevating the usage complexity for the end-user, we could create a `reload` trait in the widget, and create a listener that refresh the list, and thus we can handle this behavior from outside by doing:

- User has created a new asset -> triggers an event to change the `reload` asset select trait -> the trait will listen to the change and will update the list.

What do you think?

**Comment by ingdanielguerrero** [comment]
Ok, so in that case, it wouldn't work! let's close this issue.
