### ISSUE TITLE
return element when there is only one in get_children

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/sepal_ui#761]
I've been trying to adapt one of my apps to the new `get_children` method and I find the method more boring than before when it returned the element when it was the unique and a list when there was more than one.

I know you wanted to be consistent with the `js methods` but our implementation is slightly different. Just to give an example, I have called 15 times `get_children` method, and it worked when it was a list and when it was a single element, now, I have to add 15 more indexes `get_children(id_="x")[0]` it's not a big deal but at least before the method was taking care of it and it simplified your code a bit.

Additionally, in my personal case it is more frequent to get the first element than find more than one, what do you think??

**Comment by 12rambau** [comment]
I'm in general -1 for multi output type (`Tuple` , `List` etc are considered single types) because I secretely dream that we can make this lib compatible with Mypy. Appart for the debugging input that IDE will give when writting nonsense code (like calling the `.size()` method on a `str`), it is making the IDE suggestions so much more powerful. In this example I will get the children of random widget and as my IDE know that the result is a List of widgets it will suggest things while typing. 
This would not work if we set the output of the method to `Union[List[v.VuetifyWidget], v.VuetifyWidget]`:
